config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'
  get 'profile/show'
  resources :messages
  resources :profile
  resources :pets
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'welcome#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :pet

  #scope :personal, -> {where("owner = ? OR petitioner = ?", current_user.id, current_user.id)}
  # Arreglar metodos TODAY
  #scope :hoy, -> { where(created_at: Date.today) }
  #scope :pendiente, -> {where(pending: true)}
  scope :recientes, -> {order("created_at DESC")}
 # def make_new_text(text)
  #	Text.create(message_id: self, user_id: self.petitioner, read: false, message: text)
  #end
  def self.personal(user)
    where("owner = ? OR petitioner = ?", user, user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_pet, only: [:new]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all.personal(current_user.id).recientes
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @pet = Pet.find(@message.pet_id)
    @petitioner = User.find(@message.petitioner)
    @owner = User.find(@message.owner)
  end

  # GET /messages/new
  def new
    @pet = Pet.find(params[:id])
    @user = User.find_by_id(@pet.user_id)
    PostMailer.UserMailer(@user.email,current_user.user_name,current_user.email,current_user.phone,@user.user_name).deliver_now
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @pet = Pet.find(@message.pet_id)
    #@message.make_new_text(params[:text])

    respond_to do |format|
      if @message.save
        @pet.status = 'p'
        @pet.requested = true
        @pet.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @pet = Pet.find(@message.pet_id)
    @pet.status = "n"
    @pet.requested = false
    @pet.save
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:owner, :petitioner, :pet_id, :text, :status)
      # params.fetch(:message, {})
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-4 text-center">
    <%= image_tag(@pet.image_url, class:"img-responsive img-circle") %>
    <h1><%= link_to @pet.name, pet_path(@pet) %></h1>
    <br>
  </div>
  <div class="col-md-8">
    <% owner = User.find(@pet.user_id) %>
    <h1>Petición de adopción para <%= link_to owner.user_name.to_s + " " + owner.user_lastname_p.to_s, profile_path(owner)  %></h1>
    <br>
    <div class="field">
      <h4>Escribe por qué quieres adoptar y qué calidad de vida le brindarás:</h4>
      <%= f.text_area :text, placeholder: "Tu mensaje aquí", class:"form-control" %>
    </div>
  </div>

  <div class="col-md-12">

      <div class="field">
        <%= f.hidden_field :status, :value => false %>
      </div>
      <div class="field">
        <%= f.hidden_field :petitioner, :value => current_user.id %>
      </div>
      <div class="field">
        <%= f.hidden_field :owner, :value => @user.id %>
      </div>
      <div class="field">
        <%= f.hidden_field :pet_id, :value => @pet.id %>
      </div>
    
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= link_to 'Cancelar petición', messages_path, class:"btn btn-danger btn-lg btn-block" %>
  </div>
  <div class="col-md-6">
    <%= f.submit "Confirmar petición", class:"btn btn-success btn-lg btn-block" %>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well fondo-crema">
        <div class="row">
          <div class="col-md-12">
            

            <p id="notice"><%= notice %></p>

            <h1>Bandeja de Entrada</h1>

            <table class="table">
              <thead>

                <tr>
                  <th>Usuario</th>
                  <th>Mascota</th>
                  <th>Fecha</th>
                  <th>Mensaje</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @messages.each do |message| %>
                  <% if current_user.id != message.petitioner %>
                    <% user = User.find(message.petitioner) %>
                  <% else %>
                    <% user = User.find(message.owner) %>
                  <% end %>
                    <% pet = Pet.find(message.pet_id) %>
                    <tr>
                      <td><%= link_to user.user_name.to_s + " " + user.user_lastname_p.to_s, profile_path(user) %></td>
                      <td><%= link_to pet.name, pet_path(pet) %></td>
                      <td><%= message.created_at.to_formatted_s(:long) %></td>
                      <td><%= message.text %></td>
                      <td><%= link_to 'Ver petición', message %></td>
                      <% if pet.status == "y" %>
                        <td><%= link_to 'Aceptada', "#", class:"btn btn-success disabled" %></td>
                      <% else %>
                        <% if message.petitioner == current_user.id %>
                          <td><%= link_to 'Cancelar petición', message, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
                        <% else %>
                          <td><%= link_to 'Rechazar petición', message, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
                        <% end %>
                      <% end %>
                    </tr>
                <% end %>
              </tbody>
            </table>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<br>
<br>
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="well fondo-crema">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/messages/show.html.erb
<br>
<br>
<div class="container">
	<div class="row">
<p id="notice"><%= notice %></p>
		<div class="col-md-8 col-md-offset-2">
			<div class="well fondo-crema">
				<div class="row">
					<div class="col-md-4 text-center">
						<%= image_tag(@pet.image_url, class:"img-responsive img-circle") %>
						<h1><%= link_to @pet.name, pet_path(@pet) %></h1>
						<br>
						<h3>Registrado por:</h3>
						<h4><%= link_to @owner.user_name.to_s + " " + @owner.user_lastname_p.to_s, profile_path(@owner) %></h4>
					</div>
					<div class="col-md-8">
						<h1>Petición de adopción de <%= link_to  @petitioner.user_name,  profile_path(@petitioner)%></h1>
						<h3><%= @petitioner.user_name %> dice:</h3>
						<p><%= @message.text %></p>
						<br>
						<h3>Datos de <%= @petitioner.user_name %></h3>
						<div class="row">
							<div class="col-md-12">
								<h4><%= @petitioner.user_name.to_s + " " + @petitioner.user_lastname_p.to_s + " " + @petitioner.user_lastname_m.to_s %></h4>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<h4>Correo:</h4>
								<p><%= @petitioner.email %></p>
							</div>
							<div class="col-md-6">
								<h4>Teléfono:</h4>
								<p><%= @petitioner.phone.to_s %></p>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h4>Dirección:</h4>
								<p><%= @petitioner.address.to_s %></p>
							</div>
						</div>
					</div>
				</div>
				<hr>
				<% if @pet.status == "y" %>
					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<a href="#" class="btn btn-block btn-lg btn-success disabled">Aceptada</a>
						</div>
					</div>
				<% else %>
					<% if @message.petitioner == current_user.id %>
						<div class="row">
							<div class="col-md-6">
								<%= link_to "Espera confirmación", "#", class:"btn btn-block btn-lg btn-default disabled" %>
							</div>
							<div class="col-md-6">
								<%= link_to "Cancelar petición", @message, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-lg btn-block btn-danger" %>
							</div>
						</div>
					<% else %>
						<div class="row">
							<div class="col-md-6">
							  <!-- Este link debe actualizar a @pet.status = "y" ESO ES TODO -->
 							  <%= form_for @pet do |t| %>
							  <%= t.hidden_field :status, :value => 'y' %>
							  <%= t.submit "Confirmar adopción", class:"btn btn-block btn-lg btn-success" %>
							  <% end %>
							</div>
							<div class="col-md-6">
								<%= link_to "Rechazar petición", @message, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-lg btn-block btn-danger" %>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>