config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'
  get 'profile/show'
  resources :messages
  resources :profile
  resources :pets
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'welcome#home'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user

#o  scope :activos, -> {where(requested: false)}
  
  def self.search(search)
    if(search)
      where("name LIKE ?", "%#{search}%")
    else
      where("name LIKE ?", "%%")
    end
  end

  def self.ordena(pets,latitude,longitude)
    pets.sort_by { |x| x.user.distance_from([latitude,longitude]) }
  end

  def self.search_distance(pets,distancia,lat,lng)
    if(distancia)
      pets.select { |pet| (pet.user.distance_from([lat,lng]))*1.6 <= distancia.to_f }
    else
      pets
    end
  end

  def self.busqueda_avanzada(aname,abreed,ahair,aage,agender,asize, adescription)
    if aname == nil
      aname = ""
    end
    if abreed == nil
      abreed = ""
    end
    if ahair == nil
      ahair = ""
    end
    if aage == nil
      aage = ""
    end
    if agender == nil
      agender = ""
    end
    if asize == nil
      asize = ""
    end
    if adescription == nil
      adescription = ""
    end
  where("name LIKE ? AND breed LIKE ? AND hair LIKE ? AND age LIKE ? AND gender LIKE ? AND size LIKE ? AND description LIKE ?",
        "%#{aname}%",
        "%#{abreed}%",
        "%#{ahair}%",
        "%#{aage}%",
        "%#{agender}%",
        "%#{asize}%",
        "%#{adescription}%")
  end
end

app/controllers/pets_controller.rb
# coding: utf-8
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    #@pets = Pet.all.activos
    if (params[:aname] != "" && params[:aname] != nil)  ||
       (params[:abreed] != "" && params[:abreed] != nil) ||
       (params[:ahair] != "" && params[:ahair] != nil) ||
       (params[:aage] != "" && params[:aage] != nil) ||
       (params[:agender] != "" && params[:agender] != nil) ||
       (params[:asize] != "" && params[:asize] != nil) ||
       (params[:adescription] != "" && params[:adescription] != nil)
      @pets = Pet.all.order('created_at ASC')
      @pets = Pet.busqueda_avanzada(params[:aname],params[:abreed],params[:ahair],params[:aage],params[:agender],params[:asize], params[:adescription])
      if params[:aradio] != ""
        @pets = Pet.search_distance(@pets,params[:aradio],params[:lat2],params[:lng2])
      end

    else
      
      if params[:search]      
        @pets = Pet.search(params[:search]).order("created_at ASC")
      else
        @pets = Pet.all.order('created_at ASC')
      end
      if (params[:search_distance] != "" && params[:search_distance] != nil)
        @pets = Pet.search_distance(@pets,params[:search_distance],params[:lat],params[:lng])
      else
      end
      if (params[:latitude] != "" && params[:latitude] != nil)
        @pets = Pet.ordena(@pets,params[:latitude],params[:longitude])
      end
    end
    
    
    @hash = @pets.map {|a| {lat: a.user.latitude, lng: a.user.longitude, infowindow: "Aquí vive:"+a.name + " \n Edad:"+ a.age } }
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @user = User.where(id: @pet.user_id)
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @message = Message.where(pet_id: @pet.id).first
    if @message != nil
      @message.destroy
    end
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :hair, :age, :gender, :size, :description, :status, :image, :user_id, :requested)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@pet) do |f| %>
      <% if @pet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
          <ul>
          <% @pet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div class="row">
      <div class="col-md-4">
        <div class="field">
          <h3>Nombre de la mascota</h3>
          <%= f.text_field :name, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h3>Raza</h3>
          <%= f.text_field :breed, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h3>Color de pelo</h3>
          <%= f.text_field :hair, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h3>Edad</h3>
            <%= f.select(:age, options_for_select([['Menos de 1 año', 'Menos de 1 año'], ['1 año', '1 año'], ['2 años', '2 años'], ['3 años', '3 años'], ['4 años', '4 años'], ['5 años', '5 años'], ['6 años', '6 años'], ['7 años', '7 años'], ['8 años', '8 años'], ['9 años', '9 años'], ['10 años', '10 años'], ['11 años', '11 años'], ['12 años', '12 años'], ['13 años', '13 años'], ['14 años', '14 años'], ['15 años', '15 años']], @pet.age), {},{class:"form-control"}) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h3>Sexo</h3>
          <%= f.select(:gender, options_for_select([['Macho', 'Macho'], ['Hembra', 'Hembra']],@pet.gender), {},{class:"form-control"}) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h3>Tamaño</h3>
          <%= f.select(:size, options_for_select([['Mini', 'Mini'], ['Pequeño', 'Pequeño'], ['Mediano', 'Mediano'], ['Grande', 'Grande'], ['Muy grande', 'Muy grande']], @pet.size), {},{class:"form-control"}) %>
        </div>
      </div>
      <div class="col-md-8">
        <div class="field">
          <h3>Descripción</h3>
          <%= f.text_area :description, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h3>Foto</h3><br>
          <%= f.file_field :image %>
        </div>  
      </div>
    </div>
          
          <div class="field">
            <%= f.hidden_field :user_id, :value => current_user.id %>
          </div>
          <div class="field">
            <%= f.hidden_field :status, :value => 'n' %>
          </div>
          <div class="field">
            <%= f.hidden_field :requested, :value => false%>
          </div>
    <div class="row">
      <div class="col-md-12 text-left">
        <br>
          <div class="actions">
            <%= f.submit "Publicar", class:"btn btn-lg btn-block boton-salmon" %>
          </div>
        
      </div>
    </div>

        <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<br>
<br>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="well fondo_crema">
				<div class="row">
					<div class="col-md-12">
						<h1 class="text-center">Editar Publicación</h1>
					</div>
				</div>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyAHVODFrOsv_uDGYhUt0ONniy29qtVMsRQ"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<div class="container">
  <p id="notice"><%= notice %></p>
  <style>
    section {
    width:350px;
    float:left;
    padding:10px;
    border: 1px solid black;
    }
  </style>
  <div class="row">
    <div class="col-md-12 text-center">
      <h1 class="titulo">Mascotas en adopción</h1>
      <din class="row">
      	<div class="col-md-12 center-block text-center">
      		
      <p>
	<div style='width: 800px;'>
	  <div id="map" style='width: 800px; height: 400px;'>
	  </div>
	  <br/>
	  <br/>

	  <%= form_tag(pets_path, :method => "get", id: "search-form") do %>
	  <div class="input-group">
	  	
		  <%= text_field_tag :search, params[:search], placeholder: "Buscar", class:"form-control" %>
		  <span class="input-group-btn">
		  	
		  <%= submit_tag "Search", class:"btn btn-primary" %>
		  </span>
	  </div>
	  <% end %>
	  <br>
	  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" >Busquedas Avanzadas</button>
	  <!-- Modal -->
	  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	    <div class="modal-dialog" role="document">
	      <div class="modal-content">
		<div class="modal-header">
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  <%= form_tag(pets_path, :method => "get", id: "search-avanced-form") do %>
		  <h4 class="modal-title" id="myModalLabel">Nombre del perrito:</h4>
		</div>
		<div class="modal-body">
		  <div class="form-group">
		    <%= text_field_tag :aname, params[:aname], placeholder: "Nombre", class:"form-control" %>
		  </div>
		  <div class="form-group">
		    <label class="sr-only" for="exampleInputAmount">Raza del perrito:</label>
		    <div class="input-group">
		      <%= text_field_tag :abreed, params[:abreed], placeholder: "Raza", class:"form-control" %>
		    </div> 
		  </div>
		  <div class="form-group">
		    <label class="sr-only" for="exampleInputAmount">Pelo del perrito:</label>
		    <div class="input-group">
		      <%= text_field_tag :ahair, params[:aheir], placeholder: "Pelo", class:"form-control" %>
		    </div>
		    <div class="form-group">
		      <label class="sr-only" for="exampleInputAmount">Edad del perrito:</label>
		      <div class="input-group">
			<%= select_tag :aage, options_for_select([['Todos', ''],['Menos de 1 año', 'Menos de 1 año'], ['1 año', '1 año'], ['2 años', '2 años'], ['3 años', '3 años'], ['4 años', '4 años'], ['5 años', '5 años'], ['6 años', '6 años'], ['7 años', '7 años'], ['8 años', '8 años'], ['9 años', '9 años'], ['10 años', '10 años'], ['11 años', '11 años'], ['12 años', '12 años'], ['13 años', '13 años'], ['14 años', '14 años'], ['15 años', '15 años']], params[:aage]), {class:"form-control"} %>
		      </div> 
		    </div>
		  </div>
		  <div class="form-group">
		    <label class="sr-only" for="exampleInputAmount">Género del perrito::</label>
		    <div class="input-group">
		      <%= select_tag :agender, options_for_select([['Indiferente', ''],['Macho', 'Macho'], ['Hembra', 'Hembra']], params[:agender]), {class:"form-control"} %>
		    </div> 
		  </div>
		  <div class="form-group">
		    <label class="sr-only" for="exampleInputAmount">Tamaño del perrito:</label>
		    <div class="input-group">
		      <%= select_tag :asize, options_for_select([['Todas',''],['Mini', 'Mini'], ['Pequeño', 'Pequeño'], ['Mediano', 'Mediano'], ['Grande', 'Grande'], ['Muy grande', 'Muy grande']], params[:asize]), {class:"form-control"} %>
		    </div> 
		  </div>
		  <div class="form-group">
		    <label class="sr-only" for="exampleInputAmount">Descipción del perrito:</label>
		    <div class="input-group">
		      <%= text_field_tag :adescription, params[:adescription], placeholder: "Descripcion", class:"form-control" %>
		    </div> 
		  </div>
		  <% if current_user != nil %>
		  <div class="form-group">
		    <label class="sr-only" for="exampleInputAmount">Radio de búsqueda en Km:</label>
		    <div class="input-group">
		      <%= number_field_tag :aradio, params[:aradio], placeholder: "Radio en km" %>
		    </div> 
		  </div>
		  <%= hidden_field_tag :lat2, current_user.latitude %>
		  <%= hidden_field_tag :lng2, current_user.longitude %>
		  <% end %>
		  <div class="modal-footer">
		    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
		    <%= submit_tag "Buscar a mi perrito", class:"btn btn-primary" %>		    
		  </div>
		</div>
	      </div>
	    </div>
	  </div>
	  <% end %>
	  <% if current_user != nil %>
	  <%= link_to "Organizar por distancia", :latitude => current_user.latitude, :longitude => current_user.longitude %>
	  <% end %>
	  <br/>
	  <br/>
	  <%= link_to "Organizar por fecha" %>
	  <% if current_user != nil %>
	  <%= form_tag(pets_path, :method => "get", id: "search_distance-form") do %>
		<div class="input-group">
			
		  <%= number_field_tag :search_distance, params[:search_distance], placeholder: "Radio de búsqueda km: ∞", class:"form-control" %>
		  <%= hidden_field_tag :lat, current_user.latitude %>
		  <%= hidden_field_tag :lng, current_user.longitude %>
		  <span class="input-group-btn">
		  	<%= submit_tag "Cambiar el radio de búsqueda", class:"btn btn-primary" %>
		  </span>
		</div>
	  <% end %>
	  <% end %>
      </p>
      	</div>
      </din>
      <br/>
      <br/>
      </div>
    </div>
  <br>
  <br/>
  <div class="row">
    <% for pet in @pets %>
      <div class="col-md-3 col-sm-6">
        <div class="thumbnail shadow">
          <%= image_tag(pet.image_url, class:"img-rounded") %>
          <div class="caption">
            <h2 class="text-center"><%= pet.name %></h2>
            <h4>Raza: <span style="font-size: 15px;"><%= pet.breed %></span> </h4>
            <h4>Tamaño: <span style="font-size: 15px;"><%= pet.size %></span></h4>
            <h4>Edad: <span style="font-size: 15px;"><%= pet.age %></span></h4>
            <h4>Género: <span style="font-size: 15px;"><%= pet.gender %></span></h4>
            <%= link_to "Conóceme",pet, class:"btn btn-block boton-salmon"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
  <script type="text/javascript">    
  handler = Gmaps.build('Google');
  handler.buildMap({
  provider: {
  disableDefaultUI: false
  // pass in other Google Maps API options here
  },
  internal: {
  id: 'map'
  }
  },
  function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  }
  );
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"/>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"/>
  <script src="bootstrap.min.js"/>
  <script src="docs/assets/js/ie10-viewport-bug-workaround.js"/>

app/views/pets/new.html.erb
<br>
<br>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="well fondo-crema">
				<div class="row">
					<div class="col-md-12">
						<h1 class="text-center">Nueva Publicación</h1>
					</div>
				</div>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<div class="container">
  <br>
  <br>
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="well">
        <div class="row">
          <div class="col-md-4">
            <div class="row">
              <div class="col-md-8 col-md-offset-2">
                <%= image_tag(@pet.image_url, class:"img-responsive img-circle") %>
                <br>
              </div>
              <div class="row">
                <div class="col-md-12 text-center">
                  <h1><%= @pet.name %></h1>
                  <br>
                  <% if user_signed_in? %>
                    <% if @pet.requested == true || current_user.id == @pet.user_id %>
                    <% else %>
                    <%= link_to "¡Adóptame!", new_message_path(:id => @pet.id), class:"btn btn-lg boton-salmon"  %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-12">
                <div class="row">
                  <div class="col-md-4">
                    <h3>Raza: </h3>
                    <p><%= @pet.breed %></p>
                  </div>
                  <div class="col-md-4">
                    <h3>Edad: </h3>
                    <p><%= @pet.age %></p>
                  </div>
                  <div class="col-md-4">
                    <h3>Color de pelo: </h3>
                    <p><%= @pet.hair %></p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <h3>Género:</h3>
                    <p><%= @pet.gender %></p>
                  </div>
                  <div class="col-md-4">
                    <h3>Tamaño:</h3>
                    <p><%= @pet.size %></p>
                  </div>
                  <div class="col-md-4">
                    <h3>Estado: </h3>
                    <% if @pet.status == 'y' %>
                    <p class="salmon">Adoptado</p>
                    <% elsif @pet.status == 'n' %>
                    <p class="green">En espera de un hogar</p>
                    <% elsif @pet.status == 'p' %>
                    <p class="yellow">Tiene petición de adopción</p>
                    <% end %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <h3>Acerca de <%= @pet.name %>:</h3>
                    <p><%= @pet.description %></p>
                  </div>
                  <div class="col-md-12">
                    <% if @pet.user == current_user %>
                    <h3>Registrado por: <%= link_to @pet.user.email, profile_index_path  %></h3>		    
                    <% else %>
                    <h3>Registrado por: <%= link_to @pet.user.email, profile_path(@pet.user)  %></h3>
                    <% end %>
		    <h4> Vivo por aquí: </h4>
		    <div style='width: 400px;'>
		      <div id="map" style='width: 400px; height: 200px;'></div>
		    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if user_signed_in? %>
        <% if @pet.user_id == current_user.id %>
        <div class="text-right">
        <%= link_to 'Editar info', edit_pet_path(@pet), class:"btn btn-info btn-lg" %>
        <%= link_to 'Eliminar publicación', @pet, method: :delete, class: "btn btn-danger btn-lg" %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to 'Back', pets_path %>
</div>
<script>
  var map;
  function initMap() {
  var myLatLng = {lat: <%= @pet.user.latitude %>, lng: <%= @pet.user.longitude %>};
  
  var map = new google.maps.Map(document.getElementById('map'), {
  center: myLatLng,
  zoom: 14,
  zoomControl: true,
  mapTypeControl: true,
  scaleControl: true,
  streetViewControl: true,
  rotateControl: true
  });

  var marker = new google.maps.Marker({
  position: myLatLng,
  map: map,
  title: 'Hello World!'
  });

  var cityCircle = new google.maps.Circle({
  strokeColor: '#FF0000',
  strokeOpacity: 0.8,
  strokeWeight: 2,
  fillColor: '#FF0000',
  fillOpacity: 0.35,
  map: map,
  center: myLatLng,
  radius: 1000
  });

  
  }
  
  </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHVODFrOsv_uDGYhUt0ONniy29qtVMsRQ&callback=initMap"
	        async defer></script>